workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter build iOS
        script: |
          # O comando 'flutter build ios' em um Mac real (Codemagic)
          # cria automaticamente o Podfile e instala as dependências se necessário.
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - seu-email@exemplo.com # Mude para seu e-mail
