workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Initialize iOS and Force 15.0
        script: |
          # Gera os arquivos de infraestrutura do iOS na máquina do Codemagic
          flutter build ios --simulator --config-only
          # Força a versão 15.0 no arquivo do projeto
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 13.0/IPHONEOS_DEPLOYMENT_TARGET = 15.0/g' ios/Runner.xcodeproj/project.pbxproj
          # Instala as dependências
          cd ios && pod install
      - name: Flutter build iOS (Simulator)
        script: |
          flutter build ios --simulator --debug
    artifacts:
      - build/ios/iphonesimulator/*.app
    publishing:
      email:
        recipients:
          - seu-email@exemplo.com # Mude para seu e-mail
