// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxL7NoiSk0yY6g2vLUSRb5hyF58kBsxzo',
    appId: '1:729328356052:web:857ca01d100483100b4941',
    messagingSenderId: '729328356052',
    projectId: 'glamtime-8bfea',
    authDomain: 'glamtime-8bfea.firebaseapp.com',
    storageBucket: 'glamtime-8bfea.firebasestorage.app',
    measurementId: 'G-F0Y9X9SMQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACOm1cKvLSfzvnmpQHyQmKqKXsAGwkWVI',
    appId: '1:729328356052:android:70b1355e0fee6c8c0b4941',
    messagingSenderId: '729328356052',
    projectId: 'glamtime-8bfea',
    storageBucket: 'glamtime-8bfea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSNE0wr2qf7_JGUUHU_rOJArpuJaq0-p0',
    appId: '1:729328356052:ios:f04072cc070406830b4941',
    messagingSenderId: '729328356052',
    projectId: 'glamtime-8bfea',
    storageBucket: 'glamtime-8bfea.firebasestorage.app',
    iosBundleId: 'com.glamtime.glamTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxL7NoiSk0yY6g2vLUSRb5hyF58kBsxzo',
    appId: '1:729328356052:web:857ca01d100483100b4941',
    messagingSenderId: '729328356052',
    projectId: 'glamtime-8bfea',
    authDomain: 'glamtime-8bfea.firebaseapp.com',
    storageBucket: 'glamtime-8bfea.firebasestorage.app',
    measurementId: 'G-F0Y9X9SMQJ',
  );
}
